# Generated by Django 3.0.3 on 2020-06-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_userkaryawaninfo_nomor_handphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkaryawaninfo',
            name='nomor_handphone',
        ),
    ]
