# Generated by Django 3.0.3 on 2020-06-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0003_remove_userkaryawaninfo_nomor_handphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkaryawaninfo',
            name='nomor_handphone',
            field=models.BigIntegerField(default='12'),
        ),
    ]
