# Generated by Django 3.0.3 on 2020-05-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerusahaanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('nama_perusahaan', models.CharField(default='', max_length=256)),
                ('lokasi', models.CharField(default='', max_length=256)),
                ('alamat', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPerusahaanInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
