# Generated by Django 3.0.3 on 2020-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperusahaaninfo',
            name='lokasi',
            field=models.TextField(default='', max_length=256),
        ),
    ]
