# Generated by Django 3.0.3 on 2020-06-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0003_userkaryawaninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkaryawaninfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userkaryawaninfo',
            name='nama_perusahaan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perusahaan.UserPerusahaanInfo'),
        ),
    ]
