# Generated by Django 3.0.3 on 2020-06-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0007_perusahaan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perusahaan',
        ),
    ]
