# Generated by Django 3.0.3 on 2020-06-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0008_delete_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkaryawaninfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userkaryawaninfo',
            name='nama_perusahaan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.UserPerusahaanInfo'),
        ),
    ]
