# Generated by Django 3.0.3 on 2020-06-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0010_auto_20200605_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkaryawaninfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
