# Generated by Django 3.0.3 on 2020-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0011_auto_20200605_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkaryawaninfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userkaryawaninfo',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
