# Generated by Django 3.0.3 on 2020-06-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0012_auto_20200605_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkaryawaninfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='userkaryawaninfo',
            name='nama_perusahaan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perusahaan.UserPerusahaanInfo'),
        ),
    ]
