# Generated by Django 3.0.3 on 2020-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0014_userkaryawaninfo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKaryawanInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default='', max_length=256)),
                ('nama_lengkap', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=256)),
                ('alamat', models.TextField(default='')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='UserKaryawanInfo',
        ),
    ]
