# Generated by Django 3.0.3 on 2020-06-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0016_userkaryawaninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserKaryawanInfo',
        ),
    ]
